/** Auto-generated by `npm run generate:archives`. Do not edit by hand — edit `post-export-*.csv` then re-run. */

import type { ArchiveEntry } from "./archive-types";

export const archiveEntries: readonly ArchiveEntry[] = [
  {
    "id": "testimony-by-brittany-madni-on-the-va-budget",
    "title": "Testimony by Brittany Madni on the VA Budget",
    "date": "2026-05-20",
    "summary": "Brittany Madni. Published as Testimony. Approximately 1813 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Publication"
    ],
    "publicationTypes": [
      "Testimony"
    ],
    "tags": [
      "Appropriations",
      "Congressional Budget Office (CBO)",
      "Debt",
      "Deficit",
      "Discretionary Spending",
      "Federal Budget",
      "Mandatory Spending",
      "Program Integrity",
      "Spending",
      "Veterans",
      "Veterans Affairs",
      "Waste Fraud & Abuse"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/testimony-by-brittany-madni-on-the-va-budget/",
    "wordCount": 1813,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/testimony-by-brittany-madni-on-the-va-budget/"
      }
    ]
  },
  {
    "id": "testimony-by-brittany-madni-on-the-fiscal-challenges-at-the-va",
    "title": "Testimony by Brittany Madni on the Fiscal Challenges at the VA",
    "date": "2026-03-26",
    "summary": "Brittany Madni. Published as Testimony. Approximately 2138 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Publication"
    ],
    "publicationTypes": [
      "Testimony"
    ],
    "tags": [
      "Debt",
      "Discretionary Spending",
      "Federal Budget",
      "Mandatory Spending",
      "Program Integrity",
      "Testimony",
      "Veterans",
      "Veterans Affairs",
      "Waste Fraud & Abuse"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/testimony-by-brittany-madni-on-the-fiscal-challenges-at-the-va/",
    "wordCount": 2138,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/testimony-by-brittany-madni-on-the-fiscal-challenges-at-the-va/"
      }
    ]
  },
  {
    "id": "honoring-the-founders-fiscal-vision",
    "title": "Honoring the Founders’ Fiscal Vision",
    "date": "2026-03-17",
    "summary": "Brittany Madni. Published as Op-Ed. Approximately 1000 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Op-Ed"
    ],
    "tags": [
      "Congress",
      "Debt",
      "Federal Budget",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/honoring-the-founders-fiscal-vision/",
    "wordCount": 1000,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/honoring-the-founders-fiscal-vision/"
      }
    ]
  },
  {
    "id": "a-discharge-petition-plot",
    "title": "A Discharge Petition Plot",
    "date": "2026-01-06",
    "summary": "Brittany Madni. Published as Policy Rapid Response. Approximately 930 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "Biden COVID Credits",
      "Congress",
      "Floor Procedure",
      "Healthcare",
      "Obamacare"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/a-discharge-petition-plot/",
    "wordCount": 930,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/a-discharge-petition-plot/"
      }
    ]
  },
  {
    "id": "crafting-a-successful-balanced-budget-amendment",
    "title": "Crafting a Successful Balanced Budget Amendment",
    "date": "2025-12-10",
    "summary": "Brittany Madni. Published as Op-Ed. Approximately 734 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Op-Ed"
    ],
    "tags": [
      "Debt",
      "Federal Budget",
      "Fiscal Crisis",
      "Fiscal Space",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/crafting-a-successful-balanced-budget-amendment/",
    "wordCount": 734,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/crafting-a-successful-balanced-budget-amendment/"
      }
    ]
  },
  {
    "id": "interest-payments-on-the-debt-outpace-most-countries-gdps",
    "title": "Interest Payments on the Debt Outpace Most Countries’ GDPs",
    "date": "2025-12-03",
    "summary": "Brittany Madni. Published as Policy Rapid Response. Approximately 346 words — substantive long-form publication.",
    "categoriesLabel": "The Economy, The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "Debt",
      "Deficit",
      "Economy",
      "FY 2025",
      "Interest",
      "Mandatory Spending",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/interest-payments-on-the-debt-outpace-most-countries-gdps/",
    "wordCount": 346,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/interest-payments-on-the-debt-outpace-most-countries-gdps/"
      }
    ]
  },
  {
    "id": "balancing-the-federal-budget",
    "title": "Testimony by Brittany Madni on Balancing the Federal Budget",
    "date": "2025-12-03",
    "summary": "Brittany Madni. Published as Report. Approximately 2362 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Publication"
    ],
    "publicationTypes": [
      "Report"
    ],
    "tags": [
      "Constitution",
      "Debt",
      "Federal Budget",
      "Fiscal Crisis",
      "Fiscal Limit",
      "Fiscal Space",
      "Limited Government",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/balancing-the-federal-budget/",
    "wordCount": 2362,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/balancing-the-federal-budget/"
      }
    ]
  },
  {
    "id": "a-christmas-omnibus-is-not-the-answer",
    "title": "A Christmas Omnibus Is Not the Answer",
    "date": "2025-11-05",
    "summary": "Brittany Madni. Published as Op-Ed · Policy Rapid Response. Approximately 1448 words — substantive long-form publication.",
    "categoriesLabel": "The Economy, The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Op-Ed",
      "Policy Rapid Response"
    ],
    "tags": [
      "Appropriations",
      "Discretionary Spending",
      "Earmarks",
      "Federal Budget",
      "FY 2026",
      "Government Shutdown"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/a-christmas-omnibus-is-not-the-answer/",
    "wordCount": 1448,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/a-christmas-omnibus-is-not-the-answer/"
      }
    ]
  },
  {
    "id": "the-truth-behind-the-medicaid-cuts-myth",
    "title": "The Truth Behind the Medicaid Cuts Myth",
    "date": "2025-10-30",
    "summary": "Brittany Madni. Published as Op-Ed · Report. Approximately 446 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog",
      "Publication"
    ],
    "publicationTypes": [
      "Op-Ed",
      "Report"
    ],
    "tags": [
      "Healthcare",
      "Medicaid",
      "One Big Beautiful Bill",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/the-truth-behind-the-medicaid-cuts-myth/",
    "wordCount": 446,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/the-truth-behind-the-medicaid-cuts-myth/"
      }
    ]
  },
  {
    "id": "cashing-in-on-obamacare-subsidies",
    "title": "Cashing in on Obamacare Subsidies",
    "date": "2025-10-24",
    "summary": "Brittany Madni. Published as Op-Ed. Approximately 1106 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Op-Ed"
    ],
    "tags": [
      "Biden COVID Credits",
      "Healthcare",
      "Obamacare",
      "Program Integrity",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/cashing-in-on-obamacare-subsidies/",
    "wordCount": 1106,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/cashing-in-on-obamacare-subsidies/"
      }
    ]
  },
  {
    "id": "the-obamacare-subsidy-scheme",
    "title": "The Obamacare Subsidy Scheme",
    "date": "2025-10-17",
    "summary": "Brittany Madni. Published as Infographics · Tables · & Charts. Short artifact — charts, FAQ, infographic, or explainer excerpt in CMS.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Publication",
      "Resource"
    ],
    "publicationTypes": [
      "Infographics",
      "Tables",
      "& Charts"
    ],
    "tags": [
      "Biden COVID Credits",
      "Healthcare",
      "Obamacare",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/the-obamacare-subsidy-scheme/",
    "wordCount": 12,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/the-obamacare-subsidy-scheme/"
      }
    ]
  },
  {
    "id": "subsidy-scheme-stats",
    "title": "Subsidy Scheme Stats",
    "date": "2025-10-16",
    "summary": "Brittany Madni. Published as Infographics · Tables · & Charts. Short artifact — charts, FAQ, infographic, or explainer excerpt in CMS.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Publication",
      "Resource"
    ],
    "publicationTypes": [
      "Infographics",
      "Tables",
      "& Charts"
    ],
    "tags": [
      "Biden COVID Credits",
      "Government Shutdown",
      "Healthcare",
      "Mandatory Spending",
      "Obamacare",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/subsidy-scheme-stats/",
    "wordCount": 12,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/subsidy-scheme-stats/"
      }
    ]
  },
  {
    "id": "open-season-on-regs-advancing-the-barred-owl-cra",
    "title": "Open Season on Regs: Advancing the Barred Owl CRA",
    "date": "2025-10-06",
    "summary": "Brittany Madni. Published as Op-Ed. Approximately 619 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Op-Ed"
    ],
    "tags": [
      "Congressional Review Act",
      "Regulations",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/open-season-on-regs-advancing-the-barred-owl-cra/",
    "wordCount": 619,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/open-season-on-regs-advancing-the-barred-owl-cra/"
      }
    ]
  },
  {
    "id": "the-biden-covid-credit-scheme",
    "title": "The Biden COVID Credit Scheme",
    "date": "2025-10-01",
    "summary": "Brittany Madni, Sarah Wagoner. Published as Infographics · Tables · & Charts. Short artifact — charts, FAQ, infographic, or explainer excerpt in CMS.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni",
      "Sarah Wagoner"
    ],
    "contentTypes": [
      "Publication",
      "Resource"
    ],
    "publicationTypes": [
      "Infographics",
      "Tables",
      "& Charts"
    ],
    "tags": [
      "Biden COVID Credits",
      "Government Shutdown",
      "Healthcare",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/the-biden-covid-credit-scheme/",
    "wordCount": 0,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/the-biden-covid-credit-scheme/"
      }
    ]
  },
  {
    "id": "stop-subsidizing-sex-offenders",
    "title": "Stop Subsidizing Evil: Sex Offenders on Medicaid and Obamacare",
    "date": "2025-09-29",
    "summary": "Brittany Madni. Published as Op-Ed · Policy Rapid Response. Approximately 1627 words — substantive long-form publication.",
    "categoriesLabel": "Social Programs, The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Op-Ed",
      "Policy Rapid Response"
    ],
    "tags": [
      "Biden COVID Credits",
      "COVID-19",
      "Healthcare",
      "Medicaid",
      "Obamacare",
      "Welfare"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/stop-subsidizing-sex-offenders/",
    "wordCount": 1627,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/stop-subsidizing-sex-offenders/"
      }
    ]
  },
  {
    "id": "myth-buster-the-house-passed-cr-reflects-biden-spending-levels",
    "title": "Myth Buster: The House-Passed CR Reflects Biden Spending Levels",
    "date": "2025-09-25",
    "summary": "Brittany Madni. Published as Policy Rapid Response. Approximately 1146 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "Appropriations",
      "Continuing Resolution (CR)",
      "Discretionary Spending",
      "Government Shutdown",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/myth-buster-the-house-passed-cr-reflects-biden-spending-levels/",
    "wordCount": 1146,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/myth-buster-the-house-passed-cr-reflects-biden-spending-levels/"
      }
    ]
  },
  {
    "id": "major-wins-in-the-one-big-beautiful-bill",
    "title": "Major Wins in the One Big Beautiful Bill",
    "date": "2025-08-06",
    "summary": "Paul Winfree, Ph.D., Brittany Madni, Matthew Dickerson, David Ditch, et al.. Published as Infographics · Tables · & Charts. Short artifact — charts, FAQ, infographic, or explainer excerpt in CMS.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Paul Winfree, Ph.D.",
      "Brittany Madni",
      "Matthew Dickerson",
      "David Ditch",
      "William W. Beach, D. Phil.",
      "Rachel Greszler",
      "Anthony Campau",
      "Zoe Jackman",
      "Sarah Wagoner"
    ],
    "contentTypes": [
      "Publication"
    ],
    "publicationTypes": [
      "Infographics",
      "Tables",
      "& Charts"
    ],
    "tags": [
      "Border Security",
      "Energy",
      "Food Stamps",
      "Medicaid",
      "One Big Beautiful Bill",
      "Reconciliation",
      "Regulations",
      "Spectrum Auctions",
      "Spending",
      "Taxes"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/major-wins-in-the-one-big-beautiful-bill/",
    "wordCount": 8,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/major-wins-in-the-one-big-beautiful-bill/"
      }
    ]
  },
  {
    "id": "2025-sotu-epic-solutions",
    "title": "President Trump’s 2025 Joint Address to Congress – and EPIC’s Proposed Solutions",
    "date": "2025-03-05",
    "summary": "Paul Winfree, Ph.D., Brittany Madni, Matthew Dickerson, Zoe Jackman, et al.. Published as Policy Rapid Response. Approximately 2598 words — substantive long-form publication.",
    "categoriesLabel": "The Economy, The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Paul Winfree, Ph.D.",
      "Brittany Madni",
      "Matthew Dickerson",
      "Zoe Jackman",
      "William W. Beach, D. Phil.",
      "Anthony Campau",
      "Rachel Greszler",
      "David Ditch",
      "Amelia Kuntzman",
      "Sarah Wagoner"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "2025 Fiscal Cliff",
      "Federal Budget",
      "Reconciliation",
      "SOTU",
      "Spending",
      "Trump Administration"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/2025-sotu-epic-solutions/",
    "wordCount": 2598,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/2025-sotu-epic-solutions/"
      }
    ]
  },
  {
    "id": "epic-faqs-budget-reconciliation",
    "title": "EPIC FAQs: Budget Reconciliation",
    "date": "2025-02-07",
    "summary": "Brittany Madni, Matthew Dickerson. Published as FAQs. Approximately 3072 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni",
      "Matthew Dickerson"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "FAQs"
    ],
    "tags": [
      "Budget Resolution",
      "Reconciliation",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/epic-faqs-budget-reconciliation/",
    "wordCount": 3072,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/epic-faqs-budget-reconciliation/"
      }
    ]
  },
  {
    "id": "epic-explainer-the-2025-fiscal-cliff",
    "title": "EPIC EXPLAINER: The 2025 Fiscal Cliff",
    "date": "2025-01-01",
    "summary": "Brittany Madni, Matthew Dickerson. Published as EPIC Explainers. Approximately 946 words — substantive long-form publication.",
    "categoriesLabel": "The Economy, The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni",
      "Matthew Dickerson"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "2025 Fiscal Cliff",
      "Debt",
      "Debt Limit",
      "Discretionary Spending",
      "Economy",
      "Farm Bill",
      "Federal Budget",
      "Food Stamps",
      "FY 2025",
      "FY 2026",
      "Sequestration",
      "Spending",
      "Tax Cuts and Jobs Act (TCJA)"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/epic-explainer-the-2025-fiscal-cliff/",
    "wordCount": 946,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/epic-explainer-the-2025-fiscal-cliff/"
      }
    ]
  },
  {
    "id": "the-reconciliation-process-in-the-senate",
    "title": "The Reconciliation Process in the Senate",
    "date": "2024-11-18",
    "summary": "Brittany Madni, Matthew Dickerson. Published as Infographics · Tables · & Charts. Short artifact — charts, FAQ, infographic, or explainer excerpt in CMS.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni",
      "Matthew Dickerson"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "Infographics",
      "Tables",
      "& Charts"
    ],
    "tags": [
      "2025 Fiscal Cliff",
      "Budget Committee",
      "Budget Process Reform",
      "Reconciliation"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/the-reconciliation-process-in-the-senate/",
    "wordCount": 7,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/the-reconciliation-process-in-the-senate/"
      }
    ]
  },
  {
    "id": "understanding-the-byrd-rule",
    "title": "Understanding the Byrd Rule",
    "date": "2024-10-09",
    "summary": "Matthew Dickerson, Paul Winfree, Ph.D., Brittany Madni, Zoe Jackman. Published as EPIC Explainers. Approximately 1498 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Matthew Dickerson",
      "Paul Winfree, Ph.D.",
      "Brittany Madni",
      "Zoe Jackman"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "Budget Committee",
      "Budget Process Reform",
      "Budget Resolution",
      "Byrd Rule",
      "Federal Budget",
      "Reconciliation"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/understanding-the-byrd-rule/",
    "wordCount": 1498,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/understanding-the-byrd-rule/"
      }
    ]
  },
  {
    "id": "blocking-the-biden-harris-rule-to-kill-ahps",
    "title": "Blocking the Biden-Harris Rule to Kill AHPs",
    "date": "2024-09-10",
    "summary": "Brittany Madni, Anthony Campau, Kev Coleman. Published as Policy Rapid Response. Approximately 693 words — substantive long-form publication.",
    "categoriesLabel": "Education, Workforce, and Retirement",
    "authors": [
      "Brittany Madni",
      "Anthony Campau",
      "Kev Coleman"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "Administrative State",
      "Labor",
      "Regulations",
      "Rules"
    ],
    "permalink": "https://epicforamerica.org/education-workforce-retirement/blocking-the-biden-harris-rule-to-kill-ahps/",
    "wordCount": 693,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/education-workforce-retirement/blocking-the-biden-harris-rule-to-kill-ahps/"
      }
    ]
  },
  {
    "id": "the-reconciliation-process-in-the-house",
    "title": "The Reconciliation Process in the House",
    "date": "2024-08-27",
    "summary": "Brittany Madni. Published as Infographics · Tables · & Charts. Short artifact — charts, FAQ, infographic, or explainer excerpt in CMS.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "Infographics",
      "Tables",
      "& Charts"
    ],
    "tags": [
      "2025 Fiscal Cliff",
      "Budget Committee",
      "Budget Process Reform",
      "Reconciliation",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/the-reconciliation-process-in-the-house/",
    "wordCount": 7,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/the-reconciliation-process-in-the-house/"
      }
    ]
  },
  {
    "id": "bidenomics-subsidizes-nyc-trash",
    "title": "Bidenomics Slush Fund Subsidizes NYC Trash – Literally",
    "date": "2024-07-09",
    "summary": "Brittany Madni. Published as Policy Rapid Response. Approximately 434 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "Bidenomics",
      "Discretionary Spending",
      "Federal Budget",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/bidenomics-subsidizes-nyc-trash/",
    "wordCount": 434,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/bidenomics-subsidizes-nyc-trash/"
      }
    ]
  },
  {
    "id": "epic-explainer-reconciliation",
    "title": "EPIC EXPLAINER: Reconciliation",
    "date": "2024-05-30",
    "summary": "Brittany Madni, Matthew Dickerson. Published as EPIC Explainers. Approximately 257 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni",
      "Matthew Dickerson"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "Byrd Rule",
      "Federal Budget",
      "Reconciliation",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/epic-explainer-reconciliation/",
    "wordCount": 257,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/epic-explainer-reconciliation/"
      }
    ]
  },
  {
    "id": "the-byrd-rule",
    "title": "EPIC EXPLAINER: The Reconciliation Byrd Rule",
    "date": "2024-05-30",
    "summary": "Brittany Madni, Matthew Dickerson. Published as EPIC Explainers. Approximately 618 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni",
      "Matthew Dickerson"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "Byrd Rule",
      "Federal Budget",
      "Reconciliation",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/the-byrd-rule/",
    "wordCount": 618,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/the-byrd-rule/"
      }
    ]
  },
  {
    "id": "epic-explainer-the-tax-cuts-and-jobs-act",
    "title": "EPIC EXPLAINER: The Tax Cuts and Jobs Act",
    "date": "2024-04-14",
    "summary": "Brittany Madni, Matthew Dickerson. Published as EPIC Explainers. Approximately 843 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni",
      "Matthew Dickerson"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "Corporate Tax",
      "Tax Cuts and Jobs Act (TCJA)",
      "Taxes"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/epic-explainer-the-tax-cuts-and-jobs-act/",
    "wordCount": 843,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/epic-explainer-the-tax-cuts-and-jobs-act/"
      }
    ]
  },
  {
    "id": "setting-the-record-straight-on-bidenomics-state-of-the-union-2024",
    "title": "Setting the Record Straight on Bidenomics: State of the Union 2024",
    "date": "2024-03-06",
    "summary": "Matthew Dickerson, Brittany Madni, Anthony Campau, Rachel Greszler. Published as EPIC Explainers. Approximately 842 words — substantive long-form publication.",
    "categoriesLabel": "The Economy",
    "authors": [
      "Matthew Dickerson",
      "Brittany Madni",
      "Anthony Campau",
      "Rachel Greszler"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "Bidenomics",
      "Consumer Price Index (CPI)",
      "Deficit",
      "Economy",
      "Inflation",
      "Social Security",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/the-economy/setting-the-record-straight-on-bidenomics-state-of-the-union-2024/",
    "wordCount": 842,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/the-economy/setting-the-record-straight-on-bidenomics-state-of-the-union-2024/"
      }
    ]
  },
  {
    "id": "fy24-sequester-impact",
    "title": "EPIC Analysis: Sequester Impacts for Potential FY24 Spending Options",
    "date": "2024-02-28",
    "summary": "Brittany Madni, Matthew Dickerson. Published as EPIC Explainers · Infographics · Tables · & Charts. Approximately 440 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni",
      "Matthew Dickerson"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers",
      "Infographics",
      "Tables",
      "& Charts"
    ],
    "tags": [
      "Discretionary Spending",
      "FY 2024",
      "Omnibus Bill",
      "Spending",
      "Spending Caps"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/fy24-sequester-impact/",
    "wordCount": 440,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/fy24-sequester-impact/"
      }
    ]
  },
  {
    "id": "budget-resolution-vs-appropriations",
    "title": "EPIC EXPLAINER: BudRes v Approps",
    "date": "2024-02-12",
    "summary": "Brittany Madni. Published as EPIC Explainers. Approximately 381 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "Appropriations",
      "Budget Process Reform",
      "Budget Resolution",
      "Discretionary Spending",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/budget-resolution-vs-appropriations/",
    "wordCount": 381,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/budget-resolution-vs-appropriations/"
      }
    ]
  },
  {
    "id": "bidenomics-slush-fund-subsidizes-undocumented-immigration",
    "title": "Bidenomics Slush Fund Subsidizes “Undocumented” Immigration",
    "date": "2024-02-02",
    "summary": "Brittany Madni. Published as Policy Rapid Response. Approximately 1038 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "Bidenomics",
      "Border Security",
      "Discretionary Spending",
      "Immigration",
      "Slush Fund",
      "State and Local Fiscal Recovery Funds (SLFRF)"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/bidenomics-slush-fund-subsidizes-undocumented-immigration/",
    "wordCount": 1038,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/bidenomics-slush-fund-subsidizes-undocumented-immigration/"
      }
    ]
  },
  {
    "id": "cbo-reauthorization-regularizing-oversight",
    "title": "CBO Reauthorization: Regularizing Oversight",
    "date": "2024-01-30",
    "summary": "Brittany Madni. Published as Policy Rapid Response. Approximately 667 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "Budget Process Reform",
      "Congressional Budget Office (CBO)"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/cbo-reauthorization-regularizing-oversight/",
    "wordCount": 667,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/cbo-reauthorization-regularizing-oversight/"
      }
    ]
  },
  {
    "id": "fy23-vs-fy24-total-discretionary",
    "title": "EPIC Analysis: Comparative Total Discretionary Spending, FY 2023-2024",
    "date": "2024-01-13",
    "summary": "Paul Winfree, Ph.D., Brittany Madni. Published as Resource. Approximately 558 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Paul Winfree, Ph.D.",
      "Brittany Madni"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "Uncategorized"
    ],
    "tags": [
      "Discretionary Spending",
      "Economic Analysis",
      "FY 2023",
      "FY 2024",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/fy23-vs-fy24-total-discretionary/",
    "wordCount": 558,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/fy23-vs-fy24-total-discretionary/"
      }
    ]
  },
  {
    "id": "fy-24-spending-deal-comparative-tables",
    "title": "EPIC Analysis: Comparative Tables for FY24 Spending Deals",
    "date": "2024-01-10",
    "summary": "Paul Winfree, Ph.D., Brittany Madni, Matthew Dickerson. Published as EPIC Explainers. Short artifact — charts, FAQ, infographic, or explainer excerpt in CMS.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Paul Winfree, Ph.D.",
      "Brittany Madni",
      "Matthew Dickerson"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "Discretionary Spending",
      "Economic Analysis",
      "FY 2023",
      "FY 2024",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/fy-24-spending-deal-comparative-tables/",
    "wordCount": 2,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/fy-24-spending-deal-comparative-tables/"
      }
    ]
  },
  {
    "id": "whats-actually-in-the-spending-deal",
    "title": "What’s Actually in the Spending Deal",
    "date": "2024-01-08",
    "summary": "Matthew Dickerson, Brittany Madni, Paul Winfree, Ph.D.. Published as Policy Rapid Response. Approximately 1495 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Matthew Dickerson",
      "Brittany Madni",
      "Paul Winfree, Ph.D."
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "Appropriations",
      "COVID-19",
      "Discretionary Spending",
      "Federal Budget",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/whats-actually-in-the-spending-deal/",
    "wordCount": 1495,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/whats-actually-in-the-spending-deal/"
      }
    ]
  },
  {
    "id": "bidenomics-slush-fund",
    "title": "The Bidenomics Slush Fund",
    "date": "2023-12-03",
    "summary": "Paul Winfree, Ph.D., Brittany Madni. Published as Report. Approximately 3437 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Paul Winfree, Ph.D.",
      "Brittany Madni"
    ],
    "contentTypes": [
      "Publication"
    ],
    "publicationTypes": [
      "Report"
    ],
    "tags": [
      "Bidenomics",
      "Bureau of Economic Analysis (BEA)",
      "Discretionary Spending",
      "Slush Fund",
      "State and Local Fiscal Recovery Funds (SLFRF)"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/bidenomics-slush-fund/",
    "wordCount": 3437,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/bidenomics-slush-fund/"
      }
    ]
  },
  {
    "id": "the-need-for-oversight-of-arpa-anomalies",
    "title": "The Need for Oversight of ARPA Anomalies",
    "date": "2023-11-20",
    "summary": "Brittany Madni. Published as Policy Rapid Response. Approximately 698 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Blog"
    ],
    "publicationTypes": [
      "Policy Rapid Response"
    ],
    "tags": [
      "American Rescue Plan Act (ARPA)",
      "COVID-19",
      "Oversight",
      "Spending",
      "State and Local Fiscal Recovery Funds (SLFRF)",
      "Treasury"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/the-need-for-oversight-of-arpa-anomalies/",
    "wordCount": 698,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/the-need-for-oversight-of-arpa-anomalies/"
      }
    ]
  },
  {
    "id": "epic-explainers-crs",
    "title": "EPIC EXPLAINER: CRs",
    "date": "2023-09-12",
    "summary": "Brittany Madni. Published as EPIC Explainers. Approximately 389 words — substantive long-form publication.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "EPIC Explainers"
    ],
    "tags": [
      "Appropriations",
      "Budget Process Reform",
      "Discretionary Spending",
      "Government Shutdown",
      "Omnibus Bill",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/epic-explainers-crs/",
    "wordCount": 389,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/epic-explainers-crs/"
      }
    ]
  },
  {
    "id": "congressional-budget-process",
    "title": "Congressional Budget Process",
    "date": "2023-08-31",
    "summary": "Brittany Madni. Published as Infographics · Tables · & Charts. Short artifact — charts, FAQ, infographic, or explainer excerpt in CMS.",
    "categoriesLabel": "The Federal Budget: Spending, Taxes, and Debt",
    "authors": [
      "Brittany Madni"
    ],
    "contentTypes": [
      "Resource"
    ],
    "publicationTypes": [
      "Infographics",
      "Tables",
      "& Charts"
    ],
    "tags": [
      "Appropriations",
      "Budget Committee",
      "Budget Process Reform",
      "Discretionary Spending",
      "Mandatory Spending",
      "Spending"
    ],
    "permalink": "https://epicforamerica.org/federal-budget/congressional-budget-process/",
    "wordCount": 0,
    "status": "publish",
    "links": [
      {
        "label": "Read on EPIC",
        "href": "https://epicforamerica.org/federal-budget/congressional-budget-process/"
      }
    ]
  }
] as const;
